default_platform(:ios)

platform :ios do

  desc "Push a new beta build to TestFlight"
  lane :beta do
    ensure_git_status_clean
    update_build_number
    xcodegen
    create_api_key
    match(type: "appstore")
    build_app
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  desc "Run tests"
  lane :test do
    xcodegen
    run_tests(
      fail_build: false
    )
    slather
    code_coverage
  end

  private_lane :create_api_key do
    app_store_connect_api_key(
      key_id: ENV["FL_APPLE_KEY_ID"],
      issuer_id: ENV["FL_APPLE_ISSUER_ID"],
      key_content: ENV["FL_APPLE_KEY"],
      in_house: false
    )
  end
end
